# baseURL = "https://fileszero.github.io/hugo_qs/"
baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo_theme_robust"
# publishDir = "docs"

pygmentscodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsoptions = "linenos=table"