version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: Building blog pages
          command: hugo --minify


# https://t32k.me/mol/log/hugo-circleci-ghpages-2018/
# https://dotstud.io/blog/circleci-hugo-github-pages/