version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run: pwd
      - run:
          name: Git settings
          command: |
              git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
              git config --global user.name $CIRCLE_USERNAME
      - run:
          name: Building blog pages
          command: |
            rm -rf public
            git worktree add -B gh-pages public origin/gh-pages
            git submodule update
            hugo --minify
      - run:
          name: Push to gh-pages
          command: |
            cd public
            git add --all
            git commit -m "deploy from CI" --allow-empty
            cd ..
            git push origin gh-pages


# https://t32k.me/mol/log/hugo-circleci-ghpages-2018/
# https://dotstud.io/blog/circleci-hugo-github-pages/
# https://gohugo.io/hosting-and-deployment/hosting-on-github/

# git checkout --orphan gh-pages
# git reset --hard
#   >>  delete folders
# git commit --allow-empty -m "Initializing gh-pages branch"
# git push origin gh-pages
# rm -rf public
# git worktree add -B gh-pages public origin/gh-pages
# git submodule update
# hugo --minify
# cd public
# git add --all
# git commit -m "Publishing to gh-pages"
# cd ..
# git push origin gh-pages


# create deploy-key (write) on github (NO passphrase)
#    see https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
# set ssh key on CircleCI
# Project Settings -> SSH Permissions -> Add SSH Key
#   hostname = github.com
# Remove Checkout keys